Awesome books: plain JavaScript with objects
Armynerh/awesome_books pull request #1
Opened 2023-07-10 17:49 UTC by Armynerh

@ishimwepati  and @Armynerh  Implemented only a basic UI with plain HTML:

We created a collection that keeps a list of books,  using an array of objects.
We created a function to add a new book to the collection, with a title and author.
We created a function to remove a book from the collection.
We displayed all books saved in the collection in the top part of the page.
when a user clicks the "Add" button:
A new book is added to the collection.
The new book is displayed on the page.
when a user clicks the "Remove" button:
The correct book is removed from the collection.
The correct book disappears from the page.
 data is preserved in the browser's memory by using [localStorage](https://github.com/microverseinc/curriculum-html-css/blob/main/local_storage.md).
We didn't use any library or framework, use only plain JavaScript.

2023-07-10 18:43 UTC, Strangeal requested changes
Hi @Armynerh and @ishimwepati, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)
## Highlights
Well-structured files ✅
Correct use of GitHub Flow ✅
All linter checks are passing ✅
Descriptive PR title with a great summary ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-10 18:43 UTC, Strangeal commented on index.html
> +        </form>
- [ ] Great job on implementing the project as specified in the project requirement! 👏 However, there are some minor issues 🐞 that we need to address and fix before moving on to the next milestone. To do so Kindly consider the suggestions below:
   - [ ] Your `HTML` structure for your form is duplicated kindly consider removing one as it's doesn't match with the original design and certainly doesn't not create a good user experience.

2023-07-10 18:43 UTC, Strangeal commented on preserved.js
> +});
- [ ] As per the project requirements, You should store user input data in the `localStorage` such that when a user reloads their page the data stay persisted on the UI but currently your code isn't doing that. You're rather populating the data stored in the `localStorage` in the user input field instead of displaying it as an added book. Kindly consider fixing this issue as displaying the books at the top of the form as an added book is going to help create a good user experience rather than in the input field. See below for more details:
<img width="572" alt="Screenshot 2023-07-10 at 18 40 00" src="https://github.com/Armynerh/awesome_books/assets/107192076/0b16fc27-fe19-459d-bd99-c8f2d14858da">

2023-07-11 08:17 UTC, ishimwepati commented on index.html
> +        </form>
Ohh thanks a lot for your review!

2023-07-11 08:18 UTC, ishimwepati commented on preserved.js
> +});
Great , so we have implemented it now is required!

2023-07-11 20:56 UTC, Shisui6 approved these changes
Hi @Armynerh and @ishimwepati, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights 🎯
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Good commit messages ✅

## Optional suggestions 🪶

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-11 21:46 UTC, merged